[package]
name = "fuse2rs"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.158"

[build-dependencies]
bindgen = "0.70.1"

[dev-dependencies]
assert_cmd = "2.0.16"
cfg-if = "1.0.0"
nix = { version = "0.29.0", features = ["dir", "fs"] }
tempfile = "3.12.0"
