binop_separator = "Back"
brace_style = "SameLineWhere"
force_multiline_blocks = true
format_strings = false
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = false
max_width = 100
reorder_impl_items = true
reorder_imports = true
struct_field_align_threshold = 16
use_field_init_shorthand = true
hard_tabs = true
tab_spaces = 4
